image: ubuntu:latest

before_script:
  - apt-get update --yes > /dev/null
  - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ > /dev/null

stages:
  - build
  - test

build:
  stage: build
  script: 
    - mvn compile 
    - echo "Building the app"

test:
  stage: test
  script: echo "Running tests"
  only:
    - master
