image: ubuntu:latest

stages:
  - build
  - test

build:
  stage: build
  script: 
    - mvn compile 
    - echo "Building the app"
only: 
   - master 

test:
  stage: test
  script: echo "Running tests"
  only:
    - master
