image: maven

stages:
  - build
  - test

build:
  stage: build
  script: 
    - mvn compile 
    - echo "Building the app"
  only: 
     - hello_world_branch 

test:
  stage: test
  script: echo "Running tests"
  only:
    - hello_world_branch 
